#!/bin/bash
SCRIPT_DIR="$(
  cd $(dirname $0)
  pwd
)"
cd $SCRIPT_DIR

. functions.sh

check_env
check_version

CURRENT_VERSION=$(cat $SCRIPT_DIR/.version)
NEXT_VERSION=$(cat $SCRIPT_DIR/../themes/sass/style.scss | awk '/Version/{printf $3}')
if [ $CURRENT_VERSION = $NEXT_VERSION ]; then
  echo "different version required. CURRENT: $CURRENT_VERSION, NEXT: $NEXT_VERSION"
  exit
fi

# ビルド用ディレクトリ移動
cd $SCRIPT_DIR/../themes

# package.jsonバージョン更新
PACKAGE_VERSION=$(cat package.json | jq -r .version)
sed -i "" -e "s/\"version\": \"$PACKAGE_VERSION\"/\"version\": \"$NEXT_VERSION\"/g" package.json

# CSSファイル更新
npm run build

# 実行記録
/bin/echo -n $NEXT_VERSION >$SCRIPT_DIR/.version

echo "deploy success."
