#!/bin/bash
SCRIPT_DIR="$(
  cd $(dirname $0)
  pwd
)"
cd $SCRIPT_DIR

. functions.sh

check_env

cp $SCRIPT_DIR/../server/cms/.htaccess .htaccess
cp $SCRIPT_DIR/../server/cms/Dockerfile Dockerfile
cp $SCRIPT_DIR/../server/cms/wp-config.php wp-config.php

echo "copy settings success."

sed -i "" -e "s/http\:\/\/localhost\:8080/https\:\/\/hiroshifujita.com/g" wp-config.php
sed -i "" -e "s/'GOOGLE_ANALYTICS_ID', ''/'GOOGLE_ANALYTICS_ID', '$GOOGLE_ANALYTICS_ID'/g" wp-config.php
sed -i "" -e "s/'FB_APP_ID', ''/'FB_APP_ID', '$FB_APP_ID'/g" wp-config.php
sed -i "" -e "s/'FORCE_SSL_LOGIN', false/'FORCE_SSL_LOGIN', true/g" wp-config.php
sed -i "" -e "s/'FORCE_SSL_ADMIN', false/'FORCE_SSL_ADMIN', true/g" wp-config.php
sed -i "" -e "s/off/on/g" wp-config.php

scp -F ~/.ssh/config .htaccess $SSH_HOST:$HOME_DIR/srv/cms/.htaccess
scp -F ~/.ssh/config Dockerfile $SSH_HOST:$HOME_DIR/srv/cms/Dockerfile
scp -F ~/.ssh/config wp-config.php $SSH_HOST:$HOME_DIR/srv/cms/wp-config.php

echo "upload success."

rm .htaccess
rm Dockerfile
rm wp-config.php

echo "remove copy files success."
