#!/bin/bash
SCRIPT_DIR="$(
  cd $(dirname $0)
  pwd
)"
cd $SCRIPT_DIR

. functions.sh

check_env

cd $SCRIPT_DIR/../themes
scp -F ~/.ssh/config -r $THEME_NAME/* $SSH_HOST:$HOME_DIR/srv/cms/$THEME_NAME/

cd $SCRIPT_DIR
check_deploylog
echo $(date '+%Y/%m/%d %H:%M:%S')" "$(cat .version) >>deploy.log

echo "upload themes/ success."
